services:
  promtail-vlogs-mongodb:
    image: registry.cn-hangzhou.aliyuncs.com/hap-mdy/hap-promtail-vlogs-mongodb-amd64:1.0.0
    container_name: promtail-vlogs-mongodb
    restart: always
    network_mode: host
    environment:
      PROMTAIL_PUSH_URL: http://172.17.30.241:9428/insert/loki/api/v1/push
      PROMTAIL_USERNAME: myuser
      PROMTAIL_PASSWORD: mypassword
      PROMTAIL_JOB_NAME: mongodb-01
      PROMTAIL_LOG_PATH: /data/logs/mongodb/mongodb.log
    volumes:
      - /home/data/logs/mongodb/mongodb.log:/data/logs/mongodb/mongodb.log:ro
      - ./promtail-data:/data/promtail
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
