server:
  http_listen_port: 9081
  grpc_listen_port: 0

positions:
  filename: /data/promtail/positions.yaml

clients:
  - url: "${PROMTAIL_PUSH_URL}"
    basic_auth:
      username: "${PROMTAIL_USERNAME}"
      password: "${PROMTAIL_PASSWORD}"

    batchwait: 1s
    batchsize: 102400

    headers:
      X-Loki-Disable-Structured-Metadata: "true"

scrape_configs:
  - job_name: mongodb

    static_configs:
      - targets:
          - localhost

        labels:
          job: ${PROMTAIL_JOB_NAME}
          host: ${HOSTNAME}
          __path__: ${PROMTAIL_LOG_PATH}

    pipeline_stages:

      - json:
          expressions:
            ts: t."$date"
            c: c
            msg: msg
            attr: attr

      - timestamp:
          source: ts
          format: RFC3339

      - labels:
          c:
          msg:

      - match:
          selector: '{c!="COMMAND"}'
          action: drop

      - match:
          selector: '{msg!="Slow query"}'
          action: drop

      - json:
          source: attr
          expressions:
            durationMillis: durationMillis
            ns: ns
            planSummary: planSummary
            docsExamined: docsExamined
            reslen: reslen

      - labels:
          durationMillis:
          ns:
          planSummary:
          docsExamined:
          reslen:
          ts:
          attr:

      - template:
          source: line
          destination: line
          template: >-
            - {
              "ns":"{{ .ns }}",
              "durationMillis":"{{ .durationMillis }}",
              "planSummary":"{{ .planSummary }}",
              "docsExamined":"{{ .docsExamined }}",
              "reslen":"{{ .reslen }}",
              "attr":"{{ .attr }}"
            }

      - output:
          source: line

limits_config:
  readline_rate: 1000000
  readline_burst: 2000000
